name: wget2 Tool Build
on:
  push:
    branches-ignore:
      - trash
  schedule:
    - cron: '30 5 * * *'

jobs:
  build:
    uses: ./.github/tool_build.yml@main
    with:
      ToolName: wget2
      RequiredDeps: |
        pcre2
        libpsl
        zlib
        libhsts
        wolfcrypt
